1: s; run; I want to run away; 500
2: t; talk; Wazzap dude; 104
3: s; run; I want to run away; 200
4: s; run2; I want to eat cookies!; 1200
5: s; run3; I want to sleeep away; 1300
6: s; run4; I want to derp; 103
7: s; run5; ayyy lmao; 9001
8: s; run6; give me some of dat; 100