start:
  status: single
  text: You're on a fieldtrip at Jurassic Museum! It's been hours and the day's getting pretty hot. What do you want to do?
  choice:
    - next: AnswerTrivia
      points: 200
      text: Who cares about the heat? Jurrassic Museum is pretty interesting. I'm going to stay and play some trivia
    - next: BreakAway
      points: 500
      text: The teacher is still droning on and on about something prehistoric. Dinosaurs are cool but only up until a certain point. Quick, the teacher isn't looking now, make a break for it!


AnswerTrivia:
  status: single
  text: FILL WITH TRIVIA

BreakAway:
  status: single
  text: You're walking along when all of a sudden you see an unguaded exit and leave the park.
  conditions:
    - condition: BreakAway & BreakAway
      next: AnotherDitcher
    - condition: AnswerTrivia & BreakAway
      next: MysteryMan


AnotherDitcher:
  status: single
  text: Hey, looks like there is another kid who decided to ditch the tour. What do you want to do?
  choice:
    - name: A1
      next: Talk
      points: 100
      text: go talk to the other student
      action: help
      fallback: MysteryMan
    - name: A2
      next: MysteryMan
      points: 300
      text: walk away and continue on your own to city

Talk:
  status: single




MysteryMan:
  status: single
  text: A scruffy looking man with a strange accent approaches you. He needs your help finding a very special Princess Buttercup . . .
  choice:
    - next: 8a
      points: -100
      action: You have time to kill, might as well help out a soul!
    - next: 9a
      points: 0
      action: Walk on and ignore the man. You don't have time for shenanigans. Anyway, the guy seems pretty crazy, best stay away from him.

8a:
  status: single
  text: It turns out the mysterious man is actually Inigo Montoya and he is oh so grateful for your help. As a token of thanks, he directs you to the next intersection and even offers you bonus points if you answer the question correctly.
  special:
    event: trivia
    result: 300
  action: go to 12












End1:
  text: Alas, it appears that you've severely understimated the skills of a brooding swashbuckler. Inigo kills you (even though you swear you didn't kill his father). Perhaps if you might've survived if you had someone else with you . . .
  special:
    event: ENDING
    result: 0
